name: Bug Report
description: Report a bug in nullclaw
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?

  - type: input
    id: version
    attributes:
      label: Version
      description: "nullclaw version or commit hash"
      placeholder: "v2026.2.19"

  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Linux
        - macOS
        - Docker
        - Other
